Class swplasergun : Weapon Replaces PlasmaRifle
{
	default
	{
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 60;
		Weapon.AmmoType "Cellsy";
		Inventory.PickupMessage "$GOT_SWPLAS";
		Tag "$TAG_SWPLAS";
	}
	States
	{
		Ready:
		  DUAL A 1  A_WeaponReady;
		  Loop;
		Deselect:
		  DUAL A 1  A_Lower(12);
		  Loop;
		Select:
		  DUAL A 1  A_Raise(12);
		  Loop;
		Fire: //i promise ill do something interesting with this gun later
		  NULL A 0  A_FireProjectile("D_Laser2",0,1,4,0,0,0);
		  DUAL A 1  A_GunFlash;
		  NULL A 0  A_StartSound("FIRELASERS", CHAN_WEAPON);
		  NULL A 0  A_FireProjectile("D_Laser",0,1,4,0,0,0);
		  NULL A 0  A_SetPitch (Pitch-0.50);
		  DUAL B 1  A_GunFlash;
		  NULL A 0  A_StartSound("FIRELASERS", CHAN_WEAPON);
		  NULL A 0  A_FireProjectile("D_Laser",0,1,4,0,0,0);
		  NULL A 0  A_SetPitch (Pitch-0.50);
		  DUAL C 1  A_GunFlash;
		  NULL A 0  A_StartSound("FIRELASERS", CHAN_WEAPON);
		  DUAL CD 1 A_SetPitch (Pitch-0.50);
		  DUAL DC 1;
		  NULL A 0  A_ReFire("Fire2");
		  DUAL A 1;
		  goto Ready;
		Fire2:
		  DUAL A 0  A_FireProjectile("D_Laser2",0,1,-4,0,0,0);
		  DUAL A 1  A_GunFlash;
		  DUAL A 0  A_StartSound("FIRELASERS", CHAN_WEAPON);
		  DUAL A 0  A_FireProjectile("D_Laser",0,1,-4,0,0,0);
		  NULL A 0  A_SetPitch (Pitch-0.50);
		  DUAL B 1  A_GunFlash;
		  DUAL A 0  A_StartSound("FIRELASERS", CHAN_WEAPON);
		  DUAL A 0  A_FireProjectile("D_Laser",0,1,-4,0,0,0);
		  NULL A 0  A_SetPitch (Pitch-0.50);
		  DUAL C 1  A_GunFlash;
		  DUAL A 0  A_StartSound("FIRELASERS", CHAN_WEAPON);
		  DUAL CD 1 A_SetPitch (Pitch-0.50);
		  DUAL DC 1;
		  DUAL A 0  A_ReFire;
		  DUAL A 1;
		  goto Ready;
		Spawn:
		  DUSP A -1;
		  stop;
	}
}